resources:
- name: branch-master
  type: git
  source:
    uri: https://github.com/cahcommercial/connect-testautomation-clientops.git
    branch: Stage/PolicyConfiguration

jobs: 
- name: MavenJob
  serial: true
  plan:
  - get: branch-Stage/PolicyConfiguration
    trigger: true
  - task: mvn-test
    privileged: true
    file: branch-dev/AppDemo/pipeline.yml